@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.almostarch;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
